/**
 * Where a value comes from. One annotation, and it decides whether a control must exist.
 *
 * ## What the mark answers, and what it does not
 *
 * The criterion is **provenance, not importance**. A control is needed where the only possible
 * source of a value is a person: a passphrase, a network's name, a radio channel, the domains a
 * tunnel exists to reach. What the device measures about itself, what a subscription produced, what
 * a catalogue entry owns — a binary, a configuration file's name, a loopback port — and what this
 * product generated for its own use are not a person's to supply, and a control over one of them
 * would be a second source of truth for a fact the system already knows. A field is not marked `device` because it is obscure or rarely touched;
 * it is marked `device` because a person typing it would be typing over a measurement.
 *
 * ## Why this is a mark in the schema and not a list in the check
 *
 * The parity check has no exception list — not a parameter, not a constant, not a file. A list of
 * fields allowed to be unreachable lives far from the fields it is about, is read by nobody when a
 * field is added, and grows by one entry per inconvenient afternoon until the check passes by
 * construction. This mark sits beside the declaration instead, so it appears in the diff that
 * introduces the field, in front of the reviewer who is already deciding what the field is.
 *
 * **An unmarked field fails.** That is the whole design: the default is a loud refusal rather than a
 * silent pass, so a field added without anyone thinking about where its value comes from stops the
 * suite rather than quietly joining the set nobody has to offer a control for.
 *
 * ## Inheritance: `person` descends, the other three never do
 *
 * A mark on an object or an array applies to everything beneath it **only when it is `person`**.
 * `device`, `subscription`, `catalogue` and `generated` must be written on the leaf itself.
 *
 * This is not a stylistic preference and it is worth the extra marks it costs. Inheriting *a person
 * fills this* is safe in the only direction that matters: it can add requirements, never remove
 * them, so a field added inside such a container is required by default and a mistake shows up as a
 * missing control. Inheriting an **exemption** does the opposite — a field added inside a container
 * marked `device` would be excused from parity without anyone looking at it, which is exactly the
 * silent pass this annotation exists to prevent. The default would stop being a loud refusal at
 * precisely the positions where it matters most.
 *
 * The next reader will count the marks, see that allowing both directions would remove most of
 * them, and want to simplify. That is why the reason is written here rather than left to be
 * re-derived: the count is not the cost being managed.
 */

import type { TSchema } from '@sinclair/typebox';

/**
 * The closed set of answers to *what is the only thing that could have produced this value*.
 *
 * Closed rather than free text for the same reason the secret kinds are: free text cannot be
 * validated, so a typo becomes a field that is silently exempt from parity — the failure mode this
 * whole annotation is built against, arriving through the annotation itself.
 */
export const FIELD_SOURCES = [
  /** Only a person can supply it. A control must exist, on some screen, and parity requires one. */
  'person',
  /** The device measured or wrote it about itself. A control would be typing over a measurement. */
  'device',
  /** A subscription's feed produced it. A control would be edited away by the next refresh. */
  'subscription',
  /** The catalogue entry owns it: its binary, its configuration file's name, its loopback port. */
  'catalogue',
  /**
   * This product produced it. No person, no peer and no measurement did.
   *
   * Seven positions: `/schemaVersion`, written by `state/profiles.ts` when a migration runs;
   * `/meta/createdAt` and `/meta/updatedAt`, written by nobody on the device and travelling inside
   * the document a client sends; and the four identifiers `/uplinks/-/id`, `/tunnels/-/id`,
   * `/subscriptions/-/id` and `/tunnels/-/config/entryPoints/-/id`, generated by the interface as
   * `uplink-2`, `tunnel-3`, `subscription-1`, `entry-1` and consumed as outbound tags, systemd
   * template instances and parts of generated file names.
   *
   * The entry point's identifier joined the other three on 2026-09-21, one commit later, and the
   * gap is the thing worth reading: it was inherited `person` from its container and nobody had
   * asked the question of it, because the task of the day had been to mark six and six were marked.
   * **A criterion is not applied by the diff that introduces it; it is applied by somebody going
   * back over what the diff did not look at.** It is marked by the same argument as the other
   * three, which is the only argument that admits it: this product is the only possible author of
   * the value.
   *
   * ## Why a fifth word rather than seven red lines
   *
   * The design said four, and a reader who counts five will want to know what the fifth is buying,
   * because every addition to this set makes the next addition easier and the set exists to be hard
   * to add to. So the argument, rather than the conclusion:
   *
   * None of the other four is true of these six. `device` means *the device measured something
   * about itself*, and a schema version is not a measurement. `subscription` and `catalogue` are
   * plainly not it. `person` would be worst of all: it is the mark that says a control must exist,
   * and marking a field `person` because a control happens to render is the exception list arriving
   * through the annotation built to prevent exception lists. Leaving them unmarked is honest on the
   * day it is written and dishonest by the end of the month, because **a check that is permanently
   * red for a legitimate reason gets ignored, and then it is worth nothing on the day it is right.**
   * Six known-good failures teach every future reader that this check's red is background noise.
   *
   * The cost is real and is accepted with its shape named: this is an exemption, and an exemption is
   * a way out. What keeps it narrow is the criterion, which is not *no person types this* — that
   * would swallow every field the device is merely good at guessing. It is **this product is the
   * only possible author of the value.** A field whose value could have come from anywhere else,
   * including from a person who wanted it different, is not `generated`, whatever writes it today.
   */
  'generated',
] as const;

export type FieldSource = (typeof FIELD_SOURCES)[number];

/** The annotation key. */
export const SOURCE_ANNOTATION = 'x-source';

/**
 * Marks where a value comes from, beside the declaration.
 *
 * Mirrors `Secret()`: a wrapper that adds one annotation key and returns the same schema type, so
 * it composes with everything and changes nothing about validation. The two are orthogonal and a
 * field may carry both — a secret's provenance is still worth stating — but a secret needs no mark
 * to be required, because layer 1 requires every position a refusal can name and no annotation can
 * excuse it.
 */
export function Source<T extends TSchema>(source: FieldSource, schema: T): T {
  return { ...schema, [SOURCE_ANNOTATION]: source } as T;
}

/** The mark on a schema node, or `null` when it carries none. */
export function sourceOf(schema: unknown): FieldSource | null {
  if (typeof schema !== 'object' || schema === null) return null;
  const value = (schema as Record<string, unknown>)[SOURCE_ANNOTATION];
  return (FIELD_SOURCES as readonly string[]).includes(String(value)) ? (value as FieldSource) : null;
}
