/**
 * The units this project ships and owns.
 *
 * Every name starts with `wf-`, and that prefix is a contract: **the reconciler may only stop,
 * restart or delete a unit whose name it generated.** A unit it did not generate is not its business.
 * That removes a category of accident with no other defence — most sharply the one where a
 * distribution's own unit is adopted, the package is reinstalled, and the configuration is silently
 * replaced by the distribution's.
 *
 * Every generated unit therefore:
 *
 * * passes its configuration path **explicitly**, so it cannot pick up a file from a shared
 *   include directory;
 * * depends on the device unit of the interface it is configured against, plus `Restart=on-failure`,
 *   because a service bound to an interface can start before that interface has an address and then
 *   fail permanently — the dependency handles the ordinary case and the restart policy handles the
 *   race;
 * * avoids a hyphen in any interface name it interpolates, because systemd escapes `-` as `\x2d` in
 *   unit names and a `BindsTo=` on a mis-escaped device unit stops the service immediately with no
 *   useful error. Names are generated to satisfy that, and the check lives where they are generated.
 */

import { PATHS, type DesiredUnit } from '../desired-state.ts';
import { DEVICE_MARK, DEVICE_MARK_RULE_PRIORITY } from '@wayfarer/schemas';

/** The device unit for an interface, as systemd names it. */
export function deviceUnitFor(interfaceName: string): string {
  if (interfaceName.includes('-')) {
    // Unreachable if names are generated through the name generator, which forbids a hyphen. Kept as
    // an assertion rather than an escaping routine on purpose: escaping here would make a hyphenated
    // name work in this one place and fail in the several others that spell an interface out.
    throw new Error(
      `cannot build a device unit for "${interfaceName}": systemd escapes "-" as "\\x2d" in unit ` +
        'names, so the resulting dependency would name a unit that does not exist',
    );
  }
  return `sys-subsystem-net-devices-${interfaceName}.device`;
}

const HEADER = (purpose: string): string =>
  [
    '# Generated by Wayfarer. Edits here are overwritten on the next apply.',
    '#',
    `# ${purpose}`,
    '#',
    '# This unit is owned exclusively by Wayfarer: nothing else on this device installs, starts or',
    '# stops it, and Wayfarer does the same for units it did not generate.',
  ].join('\n');

/**
 * The proxy core, under our own name.
 *
 * Not the distribution's unit for the same binary. Adopting it would mean writing a configuration a
 * package upgrade can replace, and sharing a unit with whatever else on the device wants to run a
 * core.
 */
/**
 * The bounds that make a crash loop end, as **one definition** rather than seven copies.
 *
 * systemd's default limit is five starts in ten seconds. With `RestartSec` at two or three seconds, five
 * restarts take longer than that window, so the counter never reaches the burst and the unit restarts for
 * ever. Measured on the bench board, 2026-09-20: `wf-supplicant@wlan0` failed against a D-Bus name
 * another process already owned, and `systemctl show` reported `NRestarts=20` with `StartLimitBurst=5` —
 * twenty restarts under a limit of five, because no five of them ever fell inside one ten-second window.
 *
 * A window wide enough to contain the burst is what makes the limit mean what it says. The unit then
 * stops in `failed`, which is a state somebody can see, rather than consuming the journal and the CPU
 * until somebody happens to look.
 *
 * **In `[Unit]`, never `[Service]`**: under `[Service]` both directives parse, are ignored, and read
 * correctly in the file.
 *
 * Factored because it was pasted into every generator, which meant retuning it was seven edits and a new
 * generator silently got the default — the very restart storm these exist to stop. The test that walks
 * every generated unit and asserts the arithmetic is what makes this safe: it is the thing that fails if
 * a new generator forgets them.
 */
const RESTART_BOUNDS = ['StartLimitIntervalSec=60', 'StartLimitBurst=5'] as const;

export function coreUnit(options: { binaryPath: string; configPath?: string }): DesiredUnit {
  const configPath = options.configPath ?? PATHS.coreConfig;
  return {
    name: 'wf-core.service',
    enabled: true,
    active: true,
    purpose: 'the proxy core: the data plane',
    content: [
      HEADER('Runs the proxy core against the generated configuration, and nothing else.'),
      '',
      '[Unit]',
      'Description=Wayfarer proxy core',
      // Requires, not just After: ordering alone lets the core start when the target failed, and a
      // core routing traffic with no ruleset is the case every rule in it exists to prevent.
      'Requires=wf-firewall-ready.target',
      /*
       * And the environment must be re-derived before the core asserts anything.
       *
       * `Requires`, not `Wants`: if the re-derivation fails, the core must not start. A device with
       * no tunnel is inconvenient; a device with a tunnel built on a stale picture of the network is
       * unreachable, and from outside that is indistinguishable from a dead board. Given the choice,
       * fail towards reachable.
       */
      'Requires=wf-rederive.service',
      'After=network.target wf-firewall-ready.target wf-rederive.service',
      // Deliberately no dependency on the daemon: the control plane must not share fate with the
      // data plane, and a core that waited for the daemon would tie the two together at boot.
      ...RESTART_BOUNDS,
      '',
      '[Service]',
      'Type=simple',
      `ExecStart=${options.binaryPath} run -c ${configPath} -D /var/lib/wayfarer/core`,
      // Checked before starting, so a generated configuration that will not parse fails here with the
      // core's own message rather than as a service that flaps.
      `ExecStartPre=${options.binaryPath} check -c ${configPath}`,
      'Restart=on-failure',
      'RestartSec=3',
      'LimitNOFILE=65536',
      // The core needs to create a tunnel device and set routes; it does not need anything else.
      'AmbientCapabilities=CAP_NET_ADMIN CAP_NET_RAW CAP_NET_BIND_SERVICE',
      'CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_RAW CAP_NET_BIND_SERVICE',
      'NoNewPrivileges=yes',
      'ProtectSystem=strict',
      'ReadWritePaths=/var/lib/wayfarer',
      'ProtectHome=yes',
      '',
      '[Install]',
      'WantedBy=multi-user.target',
      '',
    ].join('\n'),
  };
}

/**
 * The access point, as a template so one device can in principle host more than one interface's
 * worth without a second unit file to keep in step.
 *
 * `ProtectSystem=strict` and `PrivateTmp=yes` are both absent, and that is measured rather than
 * careless: `hostapd_cli` creates its own client socket under `/tmp` and hostapd replies to that
 * path, so `ProtectSystem=strict` produces "Read-only file system" and `PrivateTmp=yes` produces a
 * reply delivered into a mount namespace nobody is listening in — a timed-out command with the socket
 * present and the permissions correct. The second failure mode reports an access point with no state
 * and no clients next to a link that is working perfectly. hostapd_cli 2.10 has no option to move its
 * client socket, so a writable shared `/tmp` is the price of having access-point control at all.
 */
export function hostapdUnit(): DesiredUnit {
  return {
    name: 'wf-hostapd@.service',
    enabled: false,
    active: false,
    purpose: 'access point template; the instance is the interface name',
    content: [
      HEADER('Hosts the access point on the interface named by the instance.'),
      '',
      '[Unit]',
      'Description=Wayfarer access point on %I',
      ...RESTART_BOUNDS,
      // The interface must exist before hostapd binds it. BindsTo rather than After, so removing the
      // hardware stops the service instead of leaving it running against nothing.
      'BindsTo=sys-subsystem-net-devices-%i.device',
      'After=sys-subsystem-net-devices-%i.device systemd-networkd.service',
      // And the ruleset must be loaded before this radio carries a single client's packet. Requires,
      // not After alone: an access point serving clients with the firewall absent is the leak, and it
      // is invisible from the client side because everything works.
      'Requires=wf-firewall-ready.target',
      'After=wf-firewall-ready.target',
      '',
      '[Service]',
      'Type=simple',
      `ExecStart=/usr/sbin/hostapd ${PATHS.hostapdDir}/%i.conf`,
      // The ordinary case is covered by the dependency above; this covers the race where the address
      // has not landed yet, which otherwise makes the failure permanent.
      'Restart=on-failure',
      'RestartSec=2',
      'RuntimeDirectory=wayfarer/hostapd',
      'RuntimeDirectoryPreserve=yes',
      '# See the generator comment: neither ProtectSystem=strict nor PrivateTmp can be used here.',
      'NoNewPrivileges=yes',
      '',
      '[Install]',
      'WantedBy=multi-user.target',
      '',
    ].join('\n'),
  };
}

/**
 * Re-derives the artefacts that encode the **environment**, before the core reads them.
 *
 * Some generated values are read off the device rather than chosen in the profile — today the
 * networks the exclusion list must protect, tomorrow something else. Those are a snapshot of where
 * the device was when the plan was made, and the data plane asserts them at every boot whether or
 * not they still describe the world.
 *
 * Measured on the bench board, 2026-09-20: the board was moved to a different network, its core
 * configuration still excluded the network it used to be on, and it took a correct DHCP address and
 * answered nothing. Nothing in the design noticed, because every mechanism built so far answers "did
 * this change work?" and a boot is not a change.
 *
 * A check could only report, and at boot there is nobody to report to, so this re-derives instead.
 * It is deliberately narrow: it refreshes discovered facts and rewrites the artefacts that depend on
 * them. It does not re-plan the profile, install units, or start anything.
 */
export function rederiveUnit(options: { wayPath: string }): DesiredUnit {
  return {
    name: 'wf-rederive.service',
    enabled: true,
    active: false,
    purpose: 're-derives the environment-dependent configuration before the core reads it',
    content: [
      HEADER('Refreshes the generated values that were read off this device, before the core starts.'),
      '',
      '[Unit]',
      'Description=Wayfarer environment re-derivation',
      // After the network is configured, or the addresses it reads are the ones from before boot.
      'After=network-online.target systemd-networkd-wait-online.service',
      'Wants=network-online.target',
      'Before=wf-core.service',
      '',
      '[Service]',
      'Type=oneshot',
      // RemainAfterExit, so `Requires=` from the core is satisfied by a run that succeeded rather
      // than by a unit that happens to be running.
      'RemainAfterExit=yes',
      `ExecStart=${options.wayPath} rederive`,
      // No Restart: this either works or the core must not start. A retry loop here would turn a
      // clear refusal into a device that comes up minutes later in a state nobody chose.
      'TimeoutStartSec=120',
      '',
      '[Install]',
      'WantedBy=multi-user.target',
      '',
    ].join('\n'),
  };
}

/**
 * The backstop: after the core is up, can this device still reach the networks it is itself on?
 *
 * The guard above runs *before* the fact and therefore cannot see the fact. This one asks, once the
 * tunnel exists, whether traffic to an address the device holds still leaves by the interface that
 * holds it.
 *
 * It needs no external peer, and that is what makes it trustworthy rather than merely cheap: a
 * reachability test against an outside host cannot distinguish our fault from the network's, so it
 * would be ambiguous exactly when it mattered. This question has one possible culprit.
 *
 * On failure the core is stopped and the reason goes to the event ring, loudly. A device with no
 * tunnel can be fixed from the network; a captured device cannot be reached at all.
 */
export function routeCheckUnit(options: { wayPath: string }): DesiredUnit {
  return {
    name: 'wf-route-check.service',
    enabled: true,
    active: false,
    purpose: 'checks that the device can still reach the networks it is on, once the tunnel exists',
    content: [
      HEADER('After the core is up: no address this device holds may route into the tunnel.'),
      '',
      '[Unit]',
      'Description=Wayfarer self-reachability check',
      // Ordered after the core but deliberately NOT Requires: this unit stops the core when it
      // fails, and a requirement in that direction makes systemd stop this unit mid-flight.
      'After=wf-core.service',
      'Wants=wf-core.service',
      '',
      '[Service]',
      'Type=oneshot',
      'RemainAfterExit=yes',
      /*
       * The wait is not padding. `After=` orders against the unit starting, and the core creates its
       * tun device a moment after that — so without it this check ran before the tunnel existed and
       * reported a pass at every boot.
       */
      `ExecStart=${options.wayPath} check-routes --stop-core-on-capture --wait-for-tunnel 30`,
      'TimeoutStartSec=60',
      '',
      '[Install]',
      'WantedBy=multi-user.target',
      '',
    ].join('\n'),
  };
}

/**
 * The wireless client: the uplink half of a radio.
 *
 * Started **without** `-u`, and that is the ruling rather than an omission.
 *
 * `-u` publishes association state on D-Bus under the name `fi.w1.wpa_supplicant1`, which has exactly
 * one owner on a system. Measured on the bench board, 2026-09-20: the distribution's own
 * `wpa_supplicant.service` already held it, and our instance died on
 * `dbus: Could not request service name: already registered`, restarting for ever.
 *
 * A name with one owner is a namespace, and this project does not share a namespace — it takes its
 * own. So the event source is our own control socket under our own directory, read with `wpa_cli`
 * exactly as the access point's is read with `hostapd_cli`. Nothing foreign is stopped, masked or
 * contended for, and the arrangement is identical on a distribution that ships a supplicant and one
 * that does not.
 *
 * The radio still needs a per-interface takeover, which is the right granularity: opt-in, one
 * interface, recorded with its undo. What is refused is a device-wide grab of a service that also
 * serves radios nobody asked us to manage.
 *
 * `-D nl80211` rather than letting it choose: the automatic driver selection still falls back to the
 * long-dead `wext` on some kernels, and `wext` silently supports none of the capabilities this project
 * reads from the driver.
 */
export function supplicantUnit(): DesiredUnit {
  return {
    name: 'wf-supplicant@.service',
    enabled: false,
    active: false,
    purpose: 'wireless client template; the instance is the interface name',
    content: [
      HEADER('Associates the interface named by the instance with somebody else\'s access point.'),
      '',
      '[Unit]',
      'Description=Wayfarer wireless uplink on %I',
      ...RESTART_BOUNDS,
      'BindsTo=sys-subsystem-net-devices-%i.device',
      'After=sys-subsystem-net-devices-%i.device',
      /*
       * Deliberately **not** `Requires=wf-firewall-ready.target`.
       *
       * The access point has that dependency because it carries other people's traffic and must never
       * do so unfiltered. This interface carries ours, outbound, and ordering it behind the ruleset
       * buys nothing — while making it *depend* on the ruleset means a firewall that fails to load
       * takes the uplink with it, which is the device losing its own way back at the exact moment
       * somebody needs to reach it. Ordered after, so the usual case is still tidy; not required.
       */
      'After=wf-firewall-ready.target',
      '',
      '[Service]',
      'Type=simple',
      `ExecStart=/usr/sbin/wpa_supplicant -s -D nl80211 -i %I -c ${PATHS.supplicantDir}/%i.conf`,
      'Restart=on-failure',
      'RestartSec=2',
      // Our own control-socket directory, matching `ctrl_interface=` in the generated configuration.
      'RuntimeDirectory=wayfarer/supplicant',
      'RuntimeDirectoryPreserve=yes',
      'NoNewPrivileges=yes',
      '',
      '[Install]',
      'WantedBy=multi-user.target',
      '',
    ].join('\n'),
  };
}

export function dhcpUnit(): DesiredUnit {
  return {
    name: 'wf-dhcp@.service',
    enabled: false,
    active: false,
    purpose: 'address server template; the instance is the interface name',
    content: [
      HEADER('Hands out addresses on the interface named by the instance. Resolver disabled.'),
      '',
      '[Unit]',
      'Description=Wayfarer address service on %I',
      /*
       * After the access point on the same interface, when there is one.
       *
       * `dnsmasq` binds its sockets to the interface at start-up and exits if the interface is not
       * there. Restarting hostapd takes the interface away for a moment, so without this ordering the
       * address service starts into `unknown interface` and only recovers on its restart timer.
       * Harmless on an interface with no access point: an `After=` on a unit that does not exist is
       * satisfied immediately.
       */
      'After=wf-hostapd@%i.service',
      ...RESTART_BOUNDS,
      'BindsTo=sys-subsystem-net-devices-%i.device',
      'After=sys-subsystem-net-devices-%i.device systemd-networkd.service',
      // Handing out addresses is the moment clients start forwarding traffic, so it waits for the
      // rules too.
      'Requires=wf-firewall-ready.target',
      'After=wf-firewall-ready.target',
      '',
      '[Service]',
      'Type=simple',
      // `--conf-file` and nothing else: no include directory, so a stray file elsewhere on the device
      // cannot reach this instance. `-k` keeps it in the foreground, which is what Type=simple needs.
      `ExecStart=/usr/sbin/dnsmasq -k --conf-file=${PATHS.dhcpDir}/%i.conf`,
      // A server bound to a specific interface fails permanently if it starts before that interface
      // has an address, and the dependency above cannot cover the address, only the device.
      'Restart=on-failure',
      'RestartSec=2',
      'StateDirectory=wayfarer',
      'NoNewPrivileges=yes',
      '',
      '[Install]',
      'WantedBy=multi-user.target',
      '',
    ].join('\n'),
  };
}

/**
 * An external tunnel daemon, one instance per tunnel tag.
 *
 * Routes are not pulled, and that is not a preference. A server pushing a default-route redirect
 * takes over routing and several tunnels then fight over it; a server pushing a large private range
 * captures the management network and the device becomes unreachable. Observed: servers pushing both
 * `10.0.0.0/8` and `192.168.0.0/16`. The daemon provides an interface; the core decides routing.
 *
 * A pushed **resolver address** is not filtered, because it is needed — and it is captured by a
 * script at connect time rather than written here, because it can differ between reconnections
 * depending on which gateway answered. A value fixed at configuration time is right about half the
 * time, and the failure presents as "the tunnel is up but names do not resolve".
 */
export function openvpnUnit(options: { upScript: string }): DesiredUnit {
  return {
    name: 'wf-openvpn@.service',
    enabled: false,
    active: false,
    purpose: 'external tunnel daemon template; the instance is the tunnel id',
    content: [
      HEADER('Runs one external tunnel. Pulled routes are ignored; the pushed resolver is captured.'),
      '',
      '[Unit]',
      'Description=Wayfarer tunnel %I',
      ...RESTART_BOUNDS,
      'After=network-online.target wf-firewall-ready.target',
      'Wants=network-online.target',
      '',
      '[Service]',
      'Type=simple',
      [
        'ExecStart=/usr/sbin/openvpn',
        `--config ${PATHS.openvpnDir}/%i.conf`,
        // Take the interface and nothing else. See the note above for what the alternative costs.
        '--route-noexec',
        // Not `--route-nopull`: it also discards the pushed resolver, which is the one pulled option
        // this arrangement wants. See the generator for the measurement.
        '--pull-filter ignore redirect-gateway',
        // The pushed resolver is wanted, so it is captured by the script rather than ignored.
        `--up ${options.upScript}`,
        '--up-restart',
        '--script-security 2',
        '--setenv WAYFARER_TUNNEL %i',
      ].join(' '),
      'Restart=always',
      'RestartSec=5',
      'AmbientCapabilities=CAP_NET_ADMIN',
      'CapabilityBoundingSet=CAP_NET_ADMIN CAP_SETGID CAP_SETUID',
      'NoNewPrivileges=yes',
      'StateDirectory=wayfarer',
      // The status file's directory (`PATHS.openvpnStatusDir`) must exist before the client starts: it
      // opens the file once, and a missing directory means no status for the life of the process.
      // Preserved on stop because every instance shares it, and one tunnel stopping must not remove
      // another's status file.
      `RuntimeDirectory=${PATHS.openvpnStatusDir.replace(/^\/run\//, '')}`,
      'RuntimeDirectoryPreserve=yes',
      '',
      '[Install]',
      'WantedBy=multi-user.target',
      '',
    ].join('\n'),
  };
}

/**
 * An obfuscation transport: a local listener a tunnel points at.
 *
 * The keepalive a server pushes is overridden with a shorter local one, because such a client can
 * keep listening after its far end has died — the local socket stays open, the tunnel daemon sees
 * nothing wrong, and only a local keepalive detects the failure. Measured on one such setup: recovery
 * went from 120 seconds to 42 by ignoring the pushed value, and the nominal figure had to be chosen
 * by measurement, since a nominal 30 produced a real 61.
 */
export function transportUnit(): DesiredUnit {
  return {
    name: 'wf-transport@.service',
    enabled: false,
    active: false,
    purpose: 'obfuscation transport template; the instance is the transport id',
    content: [
      HEADER('Runs one obfuscation transport, listening locally for a tunnel to connect to.'),
      '',
      '[Unit]',
      'Description=Wayfarer transport %I',
      ...RESTART_BOUNDS,
      'After=network-online.target',
      'Wants=network-online.target',
      // Ordered before the tunnels: a listener that is not up yet is a tunnel that fails its first
      // connection and then waits out a restart interval.
      'Before=wf-openvpn@.service',
      '',
      '[Service]',
      'Type=simple',
      `ExecStart=/bin/sh ${PATHS.transportDir}/%i.sh`,
      'Restart=always',
      'RestartSec=3',
      'NoNewPrivileges=yes',
      'ProtectSystem=strict',
      `ReadWritePaths=/var/lib/wayfarer`,
      '',
      '[Install]',
      'WantedBy=multi-user.target',
      '',
    ].join('\n'),
  };
}

/**
 * Another client the core cannot replace, reached over loopback.
 *
 * Needed whenever a protocol or extension exists in a different implementation and not in the core.
 * The port is allocated by the daemon so two such tunnels cannot collide, which is checked as an
 * invariant rather than discovered when the second one fails to bind.
 */
export function socksUnit(): DesiredUnit {
  return {
    name: 'wf-socks@.service',
    enabled: false,
    active: false,
    purpose: 'external client template; the instance is the tunnel id',
    content: [
      HEADER('Runs an external client that the core reaches over a local SOCKS port.'),
      '',
      '[Unit]',
      'Description=Wayfarer external client %I',
      ...RESTART_BOUNDS,
      'After=network-online.target',
      'Wants=network-online.target',
      'Before=wf-core.service',
      '',
      '[Service]',
      'Type=simple',
      `ExecStart=/bin/sh ${PATHS.socksDir}/%i.sh`,
      'Restart=always',
      'RestartSec=3',
      'NoNewPrivileges=yes',
      '',
      '[Install]',
      'WantedBy=multi-user.target',
      '',
    ].join('\n'),
  };
}

/**
 * The unit that loads the generated ruleset — at boot and during an apply, by the same path.
 *
 * **This did not exist, and its absence was invisible.** The ruleset was generated, written to
 * `/etc/wayfarer/nftables.conf`, shown in the plan review and compared by the differ — and nothing
 * ever ran `nft -f` on it. On a device that had applied a profile and then been power-cycled, the
 * kill-switch, the IPv6 rejection, the management-port rules and the time-sync bypass were all absent
 * while every file on disk said otherwise.
 *
 * The check that normally catches this class — `is-active` **and** `is-enabled` — starts from units,
 * and this fault was a *file that no unit consumed*. That is the general rule now recorded in
 * `docs/06-apply-and-rollback.md`: every generated artefact must name the unit that loads it.
 *
 * One mechanism for both paths, and that is the point rather than a convenience. The reconciler
 * restarts this unit instead of shelling out to `nft`, so the thing exercised during an apply is
 * exactly the thing that runs at boot. Two mechanisms would mean the boot path is tested only by
 * power-cycling, which nobody does on purpose.
 *
 * `ExecStartPre` validates first, so a malformed ruleset fails the unit instead of half-loading one.
 *
 * **No `ExecStop`, deliberately.** A distribution's own nftables unit flushes on stop; for us a
 * kill-switch that disappears when a unit is stopped is a leak. Our ruleset file already deletes and
 * recreates only our own table, so a restart is self-cleaning without ever flushing rules belonging to
 * anything else on the device.
 */
export function firewallUnit(
  options: { nftPath?: string; ipPath?: string; timePorts?: number[] } = {},
): DesiredUnit {
  const nft = options.nftPath ?? '/usr/sbin/nft';
  const ipPath = options.ipPath ?? '/usr/sbin/ip';
  const timePorts = options.timePorts ?? [123];

  /**
   * One policy rule, made idempotent. `ip rule add` is not: restarting this unit without the delete
   * loop stacks another copy every time, for ever.
   */
  const policyRule = (priority: number, selector: string): string =>
    `ExecStartPost=/bin/sh -c 'while ${ipPath} rule del priority ${priority} 2>/dev/null; do :; done; ` +
    `${ipPath} rule add priority ${priority} ${selector} lookup main'`;

  /**
   * **`iif lo` on every one of these, and it is not decoration.**
   *
   * A *forwarded* packet has no socket, so it has no owning user — and the kernel's uid selector matches
   * it anyway, as uid 0. Measured on the bench board, 2026-09-21: with a bare `uidrange 0-0` rule, a
   * client's packet resolved to `1.1.1.1 from 10.44.0.103 via 192.168.77.1 dev end0` — out of the tunnel
   * table entirely, onto the physical interface, carrying a client address nothing masquerades. Clients
   * could still resolve names, because a query to this device is local rather than forwarded, and could
   * reach nothing at all. "DNS works but nothing loads" for the second time in this project, from a
   * different cause.
   *
   * `iif lo` is how a policy rule says *locally originated*. With it, the same lookup returns
   * `via 172.19.0.2 dev tun0 table 2022` for the client and `via 192.168.77.1 dev end0` for the
   * device's own traffic — which is precisely the split these rules exist to make.
   *
   * The port rules carry it for the same reason and a second one: a client's own time query is forwarded
   * traffic and belongs in the tunnel like the rest of its traffic. Only *this device's* clock correction
   * needs to bypass.
   */
  const rules = [
    policyRule(DEVICE_MARK_RULE_PRIORITY, 'uidrange 0-0 iif lo'),
    ...timePorts.flatMap((port, index) => [
      policyRule(DEVICE_MARK_RULE_PRIORITY + 1 + index * 2, `ipproto udp dport ${port} iif lo`),
      policyRule(DEVICE_MARK_RULE_PRIORITY + 2 + index * 2, `ipproto tcp dport ${port} iif lo`),
    ]),
  ];
  return {
    name: 'wf-firewall.service',
    enabled: true,
    active: true,
    purpose: 'loads the generated firewall ruleset',
    content: [
      HEADER('Loads the generated nftables ruleset. Our table only; nothing else is flushed.'),
      '',
      '[Unit]',
      'Description=Wayfarer firewall ruleset',
      // Early, before anything can carry traffic. `DefaultDependencies=no` with an explicit
      // `After=sysinit.target` is the ordering a firewall needs: rules in place before the network
      // comes up, not after it has been up for a moment.
      'DefaultDependencies=no',
      'After=sysinit.target',
      'Before=network-pre.target',
      'Wants=network-pre.target',
      'Conflicts=shutdown.target',
      'Before=shutdown.target',
      '',
      '[Service]',
      'Type=oneshot',
      'RemainAfterExit=yes',
      // Validate, then load. `nft -c -f` catches a syntax error before a partial ruleset reaches the
      // kernel, and it names the line, which is why the unit fails with a message somebody can act on.
      `ExecStartPre=${nft} -c -f ${PATHS.firewall}`,
      `ExecStart=${nft} -f ${PATHS.firewall}`,
      //
      // **The rules that keep the device's own traffic out of the tunnel.**
      //
      // The ruleset above also *marks* that traffic, and marking alone does nothing: measured on the
      // bench board, 2026-09-21, with the mark being set and nothing consulting it, `ip route get
      // <address> mark 0x1e7` returned the tunnel device exactly as the unmarked lookup did, and the
      // tunnel client's own connection to its VPN server sat inside the proxy core. The protection was
      // written, documented, and inert — and because the traffic still arrived, through the core and out
      // its direct outbound, nothing looked wrong.
      //
      // **Why these select on uid and port rather than on that mark, which is the trap worth keeping.**
      // A policy rule matching the mark *was* tried first and broke the device's own networking outright.
      // The source address is chosen on the **first** route lookup, which happens before the output hook
      // runs and therefore before the mark exists: the packet was given `172.19.0.1`, the tunnel's own
      // address. Setting the mark then triggers a reroute, and the reroute keeps a source address that is
      // still local to the machine. The result was packets leaving the physical interface carrying an
      // address the upstream network cannot route a reply to — measured: every marked connection timed
      // out while the same connection bound explicitly to a real address succeeded, and `ping -I` worked
      // because binding to an interface skips the decision entirely. A mark cannot fix a source that was
      // already chosen.
      //
      // `uidrange` and `dport` are known at the first lookup, so the right table is consulted before a
      // source is picked and the address is correct by construction rather than by correction.
      //
      // Two selectors because one does not cover the other: root-owned traffic is the tunnel clients and
      // the core itself, and the time ports are there because **the time service does not run as root** —
      // a rule written only in terms of the user misses it entirely, and that failure is self-locking,
      // since correcting a wrong clock needs a time query and transports that authenticate on a timestamp
      // refuse to connect while the clock is wrong.
      //
      // They live here rather than in a unit of their own because the ruleset and these rules are one
      // protection: a separate unit is a second thing to forget to enable.
      //
      // **Why they win whatever the core does.** The core installs its own policy rules in the 9000-9010
      // range on start and removes them on stop. Linux evaluates policy rules in ascending priority order,
      // so these are consulted before all of them — whichever was installed first, and across any number
      // of core restarts. That is a property of the priority, not of the order things happened in.
      ...rules,
      '# No ExecStop: see the generator comment. Stopping this unit must not remove the rules, and',
      '# nothing here may flush a ruleset that other software has tables in.',
      '',
      '[Install]',
      'WantedBy=multi-user.target',
      '',
    ].join('\n'),
  };
}

/**
 * A marker the tunnel units order themselves after.
 *
 * Its whole purpose is the ordering rule that earned its place: the firewall must be in place before
 * anything that talks to the network starts, because the rule letting time synchronisation bypass the
 * tunnel has to exist before the first query goes out — and a wrong clock makes every
 * timestamp-authenticated transport fail while direct connections work normally.
 *
 * It now *requires* the unit that loads the ruleset rather than merely marking a moment. The
 * consequence is deliberate and is the right way round: when the firewall unit fails, this target is
 * not reached, the core and the access point do not start, and the device serves no clients with the
 * rules absent — while management stays reachable precisely because nothing loaded.
 */
export function firewallReadyTarget(): DesiredUnit {
  return {
    name: 'wf-firewall-ready.target',
    enabled: true,
    active: true,
    purpose: 'ordering marker: the generated ruleset is loaded',
    content: [
      HEADER('Reached once the generated firewall ruleset has been loaded.'),
      '',
      '[Unit]',
      'Description=Wayfarer firewall is in place',
      // Requires, not Wants: a target reached whether or not the ruleset loaded would let the units
      // ordered after it start with no rules in place, which is the leak this ordering exists to stop.
      'Requires=wf-firewall.service',
      'After=wf-firewall.service',
      'RefuseManualStart=no',
      '',
      '[Install]',
      'WantedBy=multi-user.target',
      '',
    ].join('\n'),
  };
}

/** Every template this project ships. Installed once; instances are enabled per profile. */
export function templateUnits(options: { upScript: string; nftPath?: string; wayPath?: string; timePorts?: number[] }): DesiredUnit[] {
  const wayPath = options.wayPath ?? '/usr/local/bin/way';
  return [
    firewallUnit({ ...(options.nftPath ? { nftPath: options.nftPath } : {}), ...(options.timePorts ? { timePorts: options.timePorts } : {}) }),
    firewallReadyTarget(),
    rederiveUnit({ wayPath }),
    routeCheckUnit({ wayPath }),
    hostapdUnit(),
    supplicantUnit(),
    dhcpUnit(),
    openvpnUnit({ upScript: options.upScript }),
    transportUnit(),
    socksUnit(),
  ];
}

/**
 * Templates whose instance name is an **interface name**, and which therefore derive a device unit
 * from it.
 *
 * Only these are subject to the no-hyphen rule. It is worth being precise about, because the rule is
 * usually stated as "generated names contain no hyphen" and that is narrower than it sounds: systemd
 * escaping `-` as `\x2d` only matters when a unit name is turned *back* into a device path. A tunnel
 * id may contain a hyphen — `wf-openvpn@t-hq.service` is a perfectly good unit — because nothing
 * in that template derives `sys-subsystem-net-devices-…` from the instance. Applying the interface
 * rule to tunnel ids would reject ids the profile schema allows, for a reason that does not exist.
 */
const INTERFACE_INSTANCED_TEMPLATES = new Set(['wf-hostapd@.service', 'wf-dhcp@.service']);

/** An instance name for a template. */
export function instanceOf(template: string, instance: string): string {
  const base = template.replace(/@\.service$/, '');
  if (INTERFACE_INSTANCED_TEMPLATES.has(template) && instance.includes('-')) {
    throw new Error(
      `cannot build the instance "${base}@${instance}": this template derives a device unit from its ` +
        'instance, and systemd escapes "-" as "\\x2d" in unit names, so the dependency would name a ' +
        'unit that does not exist and BindsTo= would stop the service immediately',
    );
  }
  return `${base}@${instance}.service`;
}
