/**
 * `GET /api/docs`: the API reference, rendered for a person, generated from the same route table
 * the server actually serves.
 *
 * ## Why this renders the OpenAPI document instead of replacing it
 *
 * `GET /api/openapi.json` already exists and is generated by `@fastify/swagger` from the TypeBox
 * schemas attached to the routes. A second, hand-written page would be a second source of truth,
 * and a second source of truth that disagrees with the routes is worse than no page at all — the
 * reader cannot tell which one lied. So `/api/docs` is a **rendering** of the same document, built
 * from `app.swagger()` at request time. A route that exists appears; a route that is deleted
 * disappears; neither costs anyone a memory.
 *
 * ## The gap this file exists to close: schemas do not know about handlers
 *
 * Generated documentation documents exactly what is in the schemas, and is **silent about
 * everything the route puts somewhere else.** In this API the most important fact about an
 * endpoint — which scope a credential needs to reach it — is not in its schema at all. It lives in
 * the `preHandler` (`requireScope`), which `@fastify/swagger` neither reads nor knows exists. The
 * generated document was therefore complete, self-consistent, generated from the source of truth,
 * and quietly missing the one line an operator most needs. Nothing reports that kind of absence:
 * the value exists, the reader exists, and there is no channel between them.
 *
 * The fix is not to copy the scope into each schema by hand — that is a second source of truth
 * again, one annotation away from drift. It is to read the scope back out of the **live route
 * table**, from the same guard object the build-time check already inspects. Both halves of this
 * page then come from the routes as registered, and a new route cannot be added without both
 * halves following it: a route with no guard already refuses to build (see `server.ts`).
 *
 * Written up as a class in `docs/16-implementation-notes.md`, because anyone who generates
 * documentation from schemas will hit it.
 *
 * ## Why the page is rendered here and not by a Swagger UI
 *
 * This device is a router whose clients frequently have no route to the internet — that is often
 * the reason it exists. A documentation page that fetches its renderer from a CDN is a blank page
 * in exactly the situation the operator is in when they need it. The HTML below is produced on the
 * device, references nothing external, and costs one render per request on a CPU that is already
 * serving the panel.
 */

import type { FastifyInstance } from 'fastify';
import type { TokenScope } from '../state/store.ts';

/**
 * How a route decides who may reach it.
 *
 * Three cases rather than two, because "no scope guard" is genuinely two different things here and
 * collapsing them is how `/api/auth/password` would read as unprotected: `public` means no
 * credential at all, `authenticated` means any valid credential and no scope.
 */
export type RouteAccess = { kind: 'public' } | { kind: 'authenticated' } | { kind: 'scope'; scope: TokenScope };

/**
 * What the live route table knows about access, keyed the way the OpenAPI document spells paths.
 *
 * Fastify writes parameters as `/:id` and OpenAPI as `/{id}`. The two are joined here, in one
 * place, because a join that silently misses is how every operation would end up labelled
 * "undeclared" while looking perfectly fine.
 */
export class RouteAccessIndex {
  readonly #byKey = new Map<string, RouteAccess>();

  record(method: string, url: string, access: RouteAccess): void {
    this.#byKey.set(key(method, url), access);
  }

  lookup(method: string, path: string): RouteAccess | null {
    return this.#byKey.get(key(method, path)) ?? null;
  }

  /**
   * Every route the index knows, as `METHOD /path`.
   *
   * Read by `test/api-docs` through `app.wayfarerRouteAccess`, which is what makes the coverage
   * check a comparison of two sources rather than of one with itself. This comment said it existed
   * "for a test that wants to prove the document covers all of them" while nothing called it, and
   * the test that should have was comparing the generated document against the generated document.
   */
  keys(): string[] {
    return [...this.#byKey.keys()];
  }
}

function key(method: string, url: string): string {
  return `${method.toUpperCase()} ${url.replace(/\/:([^/]+)/g, '/{$1}')}`;
}

export interface OperationView {
  method: string;
  path: string;
  access: RouteAccess | null;
  summary: string | null;
  description: string | null;
  parameters: { name: string; where: string; required: boolean; type: string; description: string | null }[];
  requestBody: unknown | null;
  responses: { status: string; description: string | null; schema: unknown | null }[];
  /** Everything this operation does not say, stated rather than left as an absence. */
  gaps: string[];
}

export interface ApiDocumentView {
  title: string;
  version: string;
  description: string | null;
  groups: { name: string; operations: OperationView[] }[];
  schemas: { name: string; schema: unknown }[];
  /** Operations whose access could not be read off the live route table. Should always be empty. */
  undeclared: string[];
}

/** A JSON object, loosely typed: this walks a document produced by another library. */
type Json = Record<string, unknown>;

function obj(value: unknown): Json | null {
  return typeof value === 'object' && value !== null && !Array.isArray(value) ? (value as Json) : null;
}

function str(value: unknown): string | null {
  return typeof value === 'string' && value !== '' ? value : null;
}

const HTTP_METHODS = ['get', 'post', 'put', 'patch', 'delete', 'head', 'options'];

/**
 * The generated OpenAPI document with the access rules from the live route table folded in.
 *
 * This is what both `/api/openapi.json` and `/api/docs` are built from, so a tool and a person are
 * looking at the same facts. The scope appears as `x-wayfarer-access` — an extension rather than a
 * `security` entry, because OpenAPI's own security model describes *which credential*, and the
 * thing an operator needs here is *which scope on that credential*, which it has no vocabulary for.
 */
export function enrichedOpenapi(app: FastifyInstance, index: RouteAccessIndex): Json {
  const document = structuredClone(app.swagger() as Json);
  const paths = obj(document['paths']);
  if (!paths) return document;

  for (const [path, rawItem] of Object.entries(paths)) {
    const item = obj(rawItem);
    if (!item) continue;
    for (const method of HTTP_METHODS) {
      const operation = obj(item[method]);
      if (!operation) continue;
      const access = index.lookup(method, path);
      operation['x-wayfarer-access'] =
        access === null
          ? { kind: 'undeclared' }
          : access.kind === 'scope'
            ? { kind: 'scope', scope: access.scope }
            : { kind: access.kind };
      // Only the credential kinds, which is all OpenAPI can express. The scope above carries the
      // rest; see the comment on this function for why the two are not the same statement.
      operation['security'] = access?.kind === 'public' ? [] : [{ session: [] }, { bearer: [] }];
    }
  }
  return document;
}

/**
 * Flatten the enriched document into something a template can walk without re-deriving anything.
 *
 * Grouping is **derived from the path**, not from a `tags` annotation on each route. An annotation
 * is one more thing to forget on the route that gets added next year, and a route missing from the
 * page is precisely the failure this endpoint exists to prevent.
 */
export function viewOf(document: Json): ApiDocumentView {
  const info = obj(document['info']) ?? {};
  const components = obj(document['components']) ?? {};
  const componentSchemas = obj(components['schemas']) ?? {};
  const paths = obj(document['paths']) ?? {};

  const byGroup = new Map<string, OperationView[]>();
  const undeclared: string[] = [];

  for (const path of Object.keys(paths).sort()) {
    const item = obj(paths[path]);
    if (!item) continue;
    for (const method of HTTP_METHODS) {
      const operation = obj(item[method]);
      if (!operation) continue;

      const accessRaw = obj(operation['x-wayfarer-access']);
      const accessKind = str(accessRaw?.['kind']);
      const access: RouteAccess | null =
        accessKind === 'scope'
          ? { kind: 'scope', scope: String(accessRaw?.['scope']) as TokenScope }
          : accessKind === 'public' || accessKind === 'authenticated'
            ? { kind: accessKind }
            : null;
      if (access === null) undeclared.push(`${method.toUpperCase()} ${path}`);

      const gaps: string[] = [];
      const summary = str(operation['summary']);
      const description = str(operation['description']);
      if (summary === null && description === null) {
        gaps.push('No summary or description is declared on this route.');
      }

      const parameters: OperationView['parameters'] = [];
      const rawParameters = Array.isArray(operation['parameters']) ? operation['parameters'] : [];
      for (const raw of rawParameters) {
        const parameter = obj(raw);
        if (!parameter) continue;
        parameters.push({
          name: String(parameter['name'] ?? '?'),
          where: String(parameter['in'] ?? '?'),
          required: parameter['required'] === true,
          type: typeLabel(parameter['schema']),
          description: str(parameter['description']),
        });
      }

      const requestBody = bodySchema(obj(operation['requestBody']));
      if (requestBody === null && (method === 'post' || method === 'put' || method === 'patch')) {
        gaps.push('No request body schema is declared, so the body is not validated by shape.');
      }

      const responses: OperationView['responses'] = [];
      const rawResponses = obj(operation['responses']) ?? {};
      for (const status of Object.keys(rawResponses).sort()) {
        const response = obj(rawResponses[status]);
        responses.push({
          status,
          description: str(response?.['description']),
          schema: bodySchema(response),
        });
      }
      if (!responses.some((response) => response.schema !== null)) {
        gaps.push(
          'No response schema is declared, so what comes back is whatever the handler returns and is ' +
            'not serialised through a schema. The shape shown above is therefore incomplete, not empty.',
        );
      }

      const group = groupOf(path);
      const list = byGroup.get(group) ?? [];
      list.push({
        method: method.toUpperCase(),
        path,
        access,
        summary,
        description,
        parameters,
        requestBody,
        responses,
        gaps,
      });
      byGroup.set(group, list);
    }
  }

  return {
    title: str(info['title']) ?? 'API',
    version: str(info['version']) ?? 'unknown',
    description: str(info['description']),
    groups: [...byGroup.entries()]
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([name, operations]) => ({ name, operations })),
    schemas: Object.keys(componentSchemas)
      .sort()
      .map((name) => ({ name, schema: componentSchemas[name] })),
    undeclared,
  };
}

/** `/api/profiles/{id}/activate` groups under `profiles`; `/api/status` under `status`. */
function groupOf(path: string): string {
  const segments = path.split('/').filter((segment) => segment !== '');
  // `api` is on every path and says nothing.
  const meaningful = segments[0] === 'api' ? segments.slice(1) : segments;
  return meaningful[0] ?? 'other';
}

function bodySchema(holder: Json | null): unknown | null {
  const content = obj(holder?.['content']);
  if (!content) return null;
  const json = obj(content['application/json']);
  return json?.['schema'] ?? null;
}

/** A short type label for a schema, following one `$ref` so a reader sees a name rather than a link. */
export function typeLabel(raw: unknown): string {
  const schema = obj(raw);
  if (!schema) return 'any';

  const ref = str(schema['$ref']);
  if (ref) return ref.split('/').pop() ?? ref;

  if (Array.isArray(schema['enum'])) {
    return schema['enum'].map((value) => JSON.stringify(value)).join(' | ');
  }
  const constant = 'const' in schema;
  if (constant) return JSON.stringify(schema['const']);

  for (const combinator of ['anyOf', 'oneOf', 'allOf']) {
    const members = schema[combinator];
    if (Array.isArray(members)) {
      const labels = [...new Set(members.map((member) => typeLabel(member)))];
      return labels.join(combinator === 'allOf' ? ' & ' : ' | ');
    }
  }

  const type = schema['type'];
  if (type === 'array') return `array of ${typeLabel(schema['items'])}`;
  if (Array.isArray(type)) return type.join(' | ');
  if (typeof type === 'string') return type;
  if (obj(schema['properties'])) return 'object';
  return 'any';
}

/**
 * The properties of an object schema, as rows. Returns null for anything that is not an object
 * schema, so the caller can fall back to the type label rather than printing an empty table — an
 * empty table reads as "this takes nothing", which is a different claim.
 */
export function propertyRows(
  raw: unknown,
): { name: string; type: string; required: boolean; description: string | null }[] | null {
  const schema = obj(raw);
  const properties = obj(schema?.['properties']);
  if (!schema || !properties) return null;
  const required = new Set(Array.isArray(schema['required']) ? schema['required'].map(String) : []);
  return Object.keys(properties).map((name) => ({
    name,
    type: typeLabel(properties[name]),
    required: required.has(name),
    description: str(obj(properties[name])?.['description']),
  }));
}

const ESCAPES: Record<string, string> = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#39;',
};

/**
 * Everything interpolated into the page goes through this.
 *
 * Not theatre: a profile name, a provider id and a token name all reach the schema layer, and a
 * `description` in a generated document is a string this file did not write.
 */
function esc(value: string): string {
  return value.replace(/[&<>"']/g, (character) => ESCAPES[character] ?? character);
}

/**
 * Prose from a schema, with `backticked` spans turned into code.
 *
 * The descriptions are written as Markdown because that is what they are in the source and what a
 * tool reading `/api/openapi.json` expects. Rendering the one construct that actually appears is
 * worth the four lines; rendering Markdown properly would mean a parser, and a parser is a
 * dependency and an injection surface for something this page does not need.
 *
 * **Applied after escaping, never before.** The tags below are the only ones this function emits,
 * and they are built from text that has already had its angle brackets removed — so a description
 * containing HTML is still shown as text, which is the whole point of escaping it in the first
 * place.
 */
export function prose(value: string): string {
  return esc(value).replace(/`([^`]+)`/g, '<code>$1</code>');
}

function accessBadge(access: RouteAccess | null): string {
  if (access === null) {
    return '<span class="badge undeclared" title="the live route table had no entry for this operation">access not declared</span>';
  }
  if (access.kind === 'public') {
    return '<span class="badge public" title="reachable with no credential at all">no credential</span>';
  }
  if (access.kind === 'authenticated') {
    return '<span class="badge any" title="any valid session or token; no scope is checked">any credential</span>';
  }
  return `<span class="badge scope" title="a credential carrying this scope">scope: ${esc(access.scope)}</span>`;
}

function renderSchema(raw: unknown, caption: string): string {
  if (raw === null || raw === undefined) return '';
  const rows = propertyRows(raw);
  const pretty = esc(JSON.stringify(raw, null, 2));
  const table =
    rows === null || rows.length === 0
      ? `<p class="type">${esc(typeLabel(raw))}</p>`
      : `<table class="fields"><thead><tr><th>field</th><th>type</th><th></th><th>notes</th></tr></thead><tbody>${rows
          .map(
            (row) =>
              `<tr><td><code>${esc(row.name)}</code></td><td class="type">${esc(row.type)}</td><td>${
                row.required ? '<span class="req">required</span>' : '<span class="opt">optional</span>'
              }</td><td>${row.description === null ? '' : prose(row.description)}</td></tr>`,
          )
          .join('')}</tbody></table>`;
  return `<div class="schema"><h4>${esc(caption)}</h4>${table}<details><summary>JSON Schema</summary><pre>${pretty}</pre></details></div>`;
}

function renderOperation(operation: OperationView): string {
  const anchor = anchorFor(operation.method, operation.path);
  const parts: string[] = [];

  parts.push(
    `<article class="op" id="${esc(anchor)}">`,
    `<h3><span class="method ${esc(operation.method.toLowerCase())}">${esc(operation.method)}</span>` +
      `<code>${esc(operation.path)}</code>${accessBadge(operation.access)}</h3>`,
  );

  if (operation.summary) parts.push(`<p class="summary">${prose(operation.summary)}</p>`);
  if (operation.description && operation.description !== operation.summary) {
    parts.push(`<p class="description">${prose(operation.description)}</p>`);
  }

  if (operation.parameters.length > 0) {
    parts.push(
      '<h4>Parameters</h4><table class="fields"><thead><tr><th>name</th><th>in</th><th>type</th><th></th><th>notes</th></tr></thead><tbody>',
      ...operation.parameters.map(
        (parameter) =>
          `<tr><td><code>${esc(parameter.name)}</code></td><td>${esc(parameter.where)}</td>` +
          `<td class="type">${esc(parameter.type)}</td><td>${
            parameter.required ? '<span class="req">required</span>' : '<span class="opt">optional</span>'
          }</td><td>${parameter.description === null ? '' : prose(parameter.description)}</td></tr>`,
      ),
      '</tbody></table>',
    );
  }

  if (operation.requestBody !== null) parts.push(renderSchema(operation.requestBody, 'Request body'));

  for (const response of operation.responses) {
    const caption = response.description ? `${response.status} — ${response.description}` : response.status;
    if (response.schema === null) {
      parts.push(`<div class="schema"><h4>${esc(caption)}</h4><p class="type">no schema declared</p></div>`);
    } else {
      parts.push(renderSchema(response.schema, caption));
    }
  }

  if (operation.gaps.length > 0) {
    parts.push(
      '<div class="gaps"><strong>What this entry does not say</strong><ul>',
      ...operation.gaps.map((gap) => `<li>${esc(gap)}</li>`),
      '</ul></div>',
    );
  }

  parts.push('</article>');
  return parts.join('');
}

export function anchorFor(method: string, path: string): string {
  return `op-${method.toLowerCase()}-${path.replace(/[^a-zA-Z0-9]+/g, '-').replace(/^-|-$/g, '')}`;
}

/**
 * The whole page, as one string. Self-contained on purpose: no stylesheet, no script, no font and
 * no image is fetched, because the operator reading this is often on a network with no route out.
 */
export function renderApiDocs(view: ApiDocumentView): string {
  const toc = view.groups
    .map(
      (group) =>
        `<section><h3>${esc(group.name)}</h3><ul>${group.operations
          .map(
            (operation) =>
              `<li><a href="#${esc(anchorFor(operation.method, operation.path))}">` +
              `<span class="method ${esc(operation.method.toLowerCase())}">${esc(operation.method)}</span>` +
              `<code>${esc(operation.path)}</code></a></li>`,
          )
          .join('')}</ul></section>`,
    )
    .join('');

  const body = view.groups
    .map(
      (group) =>
        `<section class="group"><h2 id="group-${esc(group.name)}">${esc(group.name)}</h2>${group.operations
          .map(renderOperation)
          .join('')}</section>`,
    )
    .join('');

  const schemas = view.schemas
    .map(
      (entry) =>
        `<section class="group" id="schema-${esc(entry.name)}"><h2>${esc(entry.name)}</h2>${renderSchema(
          entry.schema,
          entry.name,
        )}</section>`,
    )
    .join('');

  const undeclared =
    view.undeclared.length === 0
      ? ''
      : `<div class="gaps"><strong>Operations whose access rule could not be read from the route table</strong><ul>${view.undeclared
          .map((entry) => `<li><code>${esc(entry)}</code></li>`)
          .join('')}</ul></div>`;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(view.title)} API</title>
<style>${STYLE}</style>
</head>
<body>
<header>
  <h1>${esc(view.title)} API <span class="version">${esc(view.version)}</span></h1>
  ${view.description === null ? '' : `<p class="lead">${esc(view.description)}</p>`}
  <p class="lead">This page is generated from the routes this daemon is serving right now — the same
  schemas it validates with, and the same guards it enforces. It cannot describe an endpoint that does
  not exist, and it cannot omit one that does. The machine-readable form of exactly these facts is at
  <a href="/api/openapi.json"><code>/api/openapi.json</code></a>.</p>
  <p class="lead">Every entry states which credential reaches it. <span class="badge scope">scope: …</span>
  means a session or a token carrying that scope; <span class="badge any">any credential</span> means any
  valid one and no scope is checked; <span class="badge public">no credential</span> means the route
  answers before authentication. Scopes come from the guard on the route itself, not from an annotation
  anybody has to remember.</p>
  ${undeclared}
</header>
<nav class="toc">${toc}</nav>
<main>${body}<h2 class="schemas-heading">Schemas</h2>${schemas}</main>
</body>
</html>`;
}

const STYLE = `
:root { color-scheme: light dark; --fg:#16181d; --bg:#fff; --muted:#5c6370; --line:#dfe2e8; --card:#f7f8fa; --code:#eef0f4; }
@media (prefers-color-scheme: dark) {
  :root { --fg:#e6e8ec; --bg:#14161a; --muted:#98a0ae; --line:#2b2f37; --card:#1a1d23; --code:#22262e; }
}
* { box-sizing: border-box; }
body { margin:0; padding:0 16px 96px; color:var(--fg); background:var(--bg); font:15px/1.55 ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,sans-serif; }
header, nav, main { max-width: 62rem; margin: 0 auto; }
header { padding: 32px 0 8px; }
h1 { font-size:1.7rem; margin:0 0 12px; }
h1 .version { font-size:.8rem; color:var(--muted); font-weight:400; vertical-align:middle; }
.lead { color:var(--muted); max-width:56rem; }
a { color:inherit; }
code { background:var(--code); padding:1px 5px; border-radius:4px; font:13px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace; }
pre { background:var(--code); padding:12px; border-radius:6px; overflow:auto; font:12px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace; }
.toc { border:1px solid var(--line); border-radius:8px; padding:8px 16px 16px; margin:24px auto; display:grid; grid-template-columns:repeat(auto-fill,minmax(15rem,1fr)); gap:0 24px; }
.toc h3 { font-size:.8rem; text-transform:uppercase; letter-spacing:.06em; color:var(--muted); margin:16px 0 6px; }
.toc ul { list-style:none; margin:0; padding:0; }
.toc li { margin:2px 0; }
.toc a { text-decoration:none; display:flex; gap:6px; align-items:baseline; }
.toc a:hover code { outline:1px solid var(--muted); }
.group { margin:40px 0; }
.group > h2 { font-size:1.2rem; text-transform:uppercase; letter-spacing:.06em; color:var(--muted); border-bottom:1px solid var(--line); padding-bottom:6px; }
.schemas-heading { font-size:1.2rem; text-transform:uppercase; letter-spacing:.06em; color:var(--muted); margin-top:64px; }
.op { border:1px solid var(--line); border-radius:8px; padding:12px 16px; margin:16px 0; background:var(--card); }
.op h3 { display:flex; flex-wrap:wrap; gap:8px; align-items:center; margin:0 0 8px; font-size:1rem; }
.method { font:700 11px/1 ui-monospace,SFMono-Regular,Menlo,monospace; letter-spacing:.05em; padding:4px 6px; border-radius:4px; border:1px solid var(--line); }
.method.get { color:#1b6b3a; } .method.post { color:#1c4fa1; } .method.put, .method.patch { color:#8a5a00; } .method.delete { color:#a12020; }
@media (prefers-color-scheme: dark) {
  .method.get { color:#6fd18f; } .method.post { color:#86b4ff; } .method.put, .method.patch { color:#e0b062; } .method.delete { color:#ff8a8a; }
}
.badge { font-size:11px; padding:3px 7px; border-radius:99px; border:1px solid var(--line); color:var(--muted); }
.badge.scope { border-color:#1c4fa1; color:#1c4fa1; }
.badge.public { border-color:#a12020; color:#a12020; }
.badge.undeclared { border-color:#a12020; color:#a12020; font-weight:700; }
@media (prefers-color-scheme: dark) { .badge.scope { border-color:#86b4ff; color:#86b4ff; } .badge.public, .badge.undeclared { border-color:#ff8a8a; color:#ff8a8a; } }
.summary { margin:6px 0; }
.description { margin:6px 0; color:var(--muted); }
h4 { font-size:.78rem; text-transform:uppercase; letter-spacing:.06em; color:var(--muted); margin:16px 0 6px; }
table.fields { width:100%; border-collapse:collapse; font-size:13px; }
table.fields th { text-align:left; font-weight:600; color:var(--muted); font-size:11px; text-transform:uppercase; letter-spacing:.05em; border-bottom:1px solid var(--line); padding:4px 8px 4px 0; }
table.fields td { border-bottom:1px solid var(--line); padding:5px 8px 5px 0; vertical-align:top; }
.type { font:12px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace; color:var(--muted); }
.req { font-size:11px; color:#a12020; } .opt { font-size:11px; color:var(--muted); }
@media (prefers-color-scheme: dark) { .req { color:#ff8a8a; } }
details summary { cursor:pointer; font-size:12px; color:var(--muted); margin:8px 0; }
.gaps { border-left:3px solid var(--muted); padding:8px 0 8px 12px; margin:16px 0 0; font-size:13px; color:var(--muted); }
.gaps ul { margin:6px 0 0; padding-left:18px; }
`;
