/**
 * **Cloak + OpenVPN** — what the owner has is an `.ovpn` file *plus* the entry points that front it.
 *
 * One catalogue entry, not a tunnel composed with a transport. The two are configured together
 * because they are chosen together: nobody has an obfuscation layer and then decides what to put
 * behind it. The composition survives in this file and stops being the owner's problem.
 *
 * ## What that buys, concretely
 *
 * Under the old shape the port appeared **twice** and nothing checked the two agreed: once as
 * `"LocalPort": "12294"` inside an opaque client-configuration string, and once as
 * `remote 127.0.0.1 12294` inside an opaque `.ovpn` blob forty lines away. The operator kept them in
 * step by hand. Here the port is allocated once, and both files are generated from that one value —
 * so the class of failure disappears rather than being documented.
 *
 * ## The file extension is part of the format, and it is ours
 *
 * These configurations are written as `.json`, deliberately. A generator naming a file `.conf` met a
 * client that infers its format from the extension, and the client did not start — silently. An
 * entry owns its configuration file's name *and* its format precisely so the two cannot be chosen by
 * different people.
 */

import type { CloakEntryPoint, CloakOpenVpnConfig } from '@wayfarer/schemas';
import { PATHS, type DesiredUnit, type ManagedFile } from '../desired-state.ts';
import type { CatalogueEntry, EntryPlanContext, EntryPlanResult } from './index.ts';
import { OPENVPN_BINARY, openVpnFailsClosed, openVpnLiveness, planOpenVpnBody } from './openvpn.ts';
import type { OvpnRemote } from './ovpn.ts';
import { secretText } from './values.ts';

/** The binary this entry runs for each entry point. Named once, here, never in a profile. */
export const CLOAK_BINARY = 'ck-client';

/**
 * The systemd instance for one entry point.
 *
 * Scoped by tunnel so an entry point id only has to be unique inside its own tunnel. It used to be a
 * bare identifier that had to be unique across the whole profile, which is a rule nobody can see
 * while editing one tunnel.
 */
export function cloakInstance(tunnelId: string, entryPointId: string): string {
  return `${tunnelId}-${entryPointId}`;
}

/**
 * The client's configuration, as this entry decides it should look.
 *
 * Field names are the client's, not ours — this is its format, and translating it would put a second
 * vocabulary between the owner and the thing that reads the file. `LocalHost` and `LocalPort` are
 * ours: a listener that binds anywhere but loopback is a proxy open to whatever network the device
 * is plugged into.
 */
function cloakConfig(entryPoint: CloakEntryPoint, port: number): string {
  const document: Record<string, unknown> = {
    Transport: entryPoint.transport,
    ProxyMethod: entryPoint.proxyMethod,
    EncryptionMethod: entryPoint.encryptionMethod,
    UID: secretText(entryPoint.uid),
    PublicKey: entryPoint.publicKey,
    ServerName: entryPoint.serverName,
    BrowserSig: entryPoint.browserSignature,
    NumConn: entryPoint.connections ?? 4,
    StreamTimeout: entryPoint.streamTimeoutSeconds ?? 300,
    RemoteHost: entryPoint.host,
    // The client wants these as strings; measured on every working entry point on the bench.
    RemotePort: `${entryPoint.port}`,
    LocalHost: '127.0.0.1',
    LocalPort: `${port}`,
    UDP: entryPoint.udp ?? true,
  };
  return `${JSON.stringify(document, null, 2)}\n`;
}

/**
 * The wrapper the unit runs.
 *
 * The argument vector is this entry's, which is the whole point of E1: nobody types `-c`, and nobody
 * can get a flag wrong in a way that stops the client silently.
 */
function cloakScript(configPath: string, port: number): string {
  return [
    '#!/bin/sh',
    '# Generated by Wayfarer. Edits here are overwritten on the next apply.',
    '#',
    '# The port below was allocated by this daemon and written into both this listener’s',
    '# configuration and the OpenVPN profile that dials it, from one value, so the two cannot',
    '# disagree. A port stated by hand in two files is how a tunnel fails to connect with both',
    '# files looking correct.',
    'set -eu',
    `WAYFARER_LOCAL_PORT=${port}`,
    'export WAYFARER_LOCAL_PORT',
    `exec ${CLOAK_BINARY} -c ${configPath}`,
    '',
  ].join('\n');
}

export const cloakOpenVpnEntry: CatalogueEntry<'cloak-openvpn'> = {
  id: 'cloak-openvpn',
  title: 'Cloak + OpenVPN',

  availability: ({ installed }) => {
    const missing = [OPENVPN_BINARY, CLOAK_BINARY].filter((binary) => !installed.has(binary));
    if (missing.length === 0) return { available: true };
    return {
      available: false,
      reason: `Not installed on this device: ${missing.join(', ')}.`,
      requires: missing.map((binary) => ({
        binary,
        neededFor: 'running an obfuscated OpenVPN tunnel',
      })),
    };
  },

  plan: (rawConfig, context: EntryPlanContext): EntryPlanResult => {
    const config = rawConfig as CloakOpenVpnConfig;

    const files: ManagedFile[] = [];
    const units: DesiredUnit[] = [];
    const remotes: OvpnRemote[] = [];

    config.entryPoints.forEach((entryPoint, entryPointIndex) => {
      const instance = cloakInstance(context.tunnel.id, entryPoint.id);
      const unit = `wf-transport@${instance}.service`;
      const configPath = `${PATHS.transportDir}/${instance}.json`;
      const port = context.allocatePort({
        owner: `entry point "${entryPoint.name ?? entryPoint.id}" of tunnel "${context.tunnel.name}"`,
        pointer: `/tunnels/${context.tunnel.index}/config/entryPoints/${entryPointIndex}`,
      });

      files.push(
        {
          path: configPath,
          content: cloakConfig(entryPoint, port),
          // 0600: this file carries the account identifier that makes the entry point work.
          mode: 0o600,
          credentials: true,
          purpose: `the obfuscation entry point "${entryPoint.id}" for "${context.tunnel.name}"`,
          consumedBy: { kind: 'unit', unit },
        },
        {
          path: `${PATHS.transportDir}/${instance}.sh`,
          content: cloakScript(configPath, port),
          mode: 0o700,
          purpose: `starts the entry point "${entryPoint.id}" for "${context.tunnel.name}"`,
          consumedBy: { kind: 'unit', unit },
        },
      );

      units.push({
        name: unit,
        enabled: true,
        active: true,
        purpose: `the entry point "${entryPoint.id}" on 127.0.0.1:${port}`,
      });

      remotes.push({
        host: '127.0.0.1',
        port,
        note:
          `entry point ${entryPointIndex + 1} of ${config.entryPoints.length}: ` +
          `${entryPoint.host}:${entryPoint.port}, presented as ${entryPoint.serverName}`,
      });
    });

    const result = planOpenVpnBody(config, context, { remotes, extraFiles: files });
    if (!result.ok) return result;

    return {
      ok: true,
      plan: {
        ...result.plan,
        units: [...units, ...result.plan.units],
      },
    };
  },

  // The same client, so the same question: the transport carries OpenVPN's own keepalive through to
  // the peer, and a transport whose far end has died stops delivering it exactly as a dead link would.
  liveness: openVpnLiveness,
  failsClosed: openVpnFailsClosed,
};
