/**
 * The `.ovpn` file, and the two things about it that are ours rather than the peer's.
 *
 * Shared by the two OpenVPN-bearing entries. Shared as a function with arguments rather than as a
 * base entry, because `Cloak + OpenVPN` is one catalogue entry and not a composition anybody
 * performs: the composition survives here, inside, and stops being the owner's problem.
 */

import { PATHS, type ManagedFile } from '../desired-state.ts';

/** Where the client should dial. Empty means the profile's own `remote` lines stand. */
export interface OvpnRemote {
  host: string;
  port: number;
  /** Why this remote is what it is, for the generated file's own comment. */
  note: string;
}

export interface OvpnFileInput {
  tunnelId: string;
  tunnelName: string;
  interfaceName: string;
  /** The `.ovpn` file the owner was given, verbatim. */
  profile: string;
  auth?: { username: string; password: string };
  /**
   * Remotes this device decides.
   *
   * When non-empty the profile's own `remote` lines are **dropped**, because they are the ones that
   * had to be kept in step by hand with a port stated somewhere else. Measured on the bench,
   * 2026-09-21: an obfuscated tunnel's `.ovpn` blob named `127.0.0.1:12294` while a separate string
   * field forty lines away declared `"LocalPort": "12294"`, and nothing checked that the two agreed.
   * Now one side decides and the other is generated from it, so they cannot disagree.
   */
  remotes: OvpnRemote[];
  /** The unit that will read these files. Named by the caller so the entry owns its unit shape. */
  unit: string;
}

/** `remote` and its relatives, dropped when this device supplies its own. */
const REMOTE_DIRECTIVES = /^\s*(remote|remote-random|remote-random-hostname)\b/;

export function ovpnFiles(input: OvpnFileInput): ManagedFile[] {
  const files: ManagedFile[] = [
    {
      path: `${PATHS.openvpnDir}/${input.tunnelId}.conf`,
      content: ovpnConfig(input),
      mode: 0o600,
      // The operator's blob: a private key, a certificate and often a `tls-crypt` static key inline.
      credentials: true,
      purpose: `the OpenVPN configuration for "${input.tunnelName}"`,
      consumedBy: { kind: 'unit', unit: input.unit },
    },
  ];

  if (input.auth !== undefined) {
    files.push({
      path: `${PATHS.openvpnDir}/${input.tunnelId}.auth`,
      content: `${input.auth.username}\n${input.auth.password}\n`,
      mode: 0o600,
      credentials: true,
      purpose: `credentials for "${input.tunnelName}"`,
      consumedBy: { kind: 'unit', unit: input.unit },
    });
  }

  return files;
}

function ovpnConfig(input: OvpnFileInput): string {
  const owned = input.profile
    .split('\n')
    .filter((line) => input.remotes.length === 0 || !REMOTE_DIRECTIVES.test(line))
    .join('\n')
    .trimEnd();

  const lines = [
    '# Generated by Wayfarer. Edits here are overwritten on the next apply.',
    '#',
    '# Routing directives from the peer are ignored: a server pushing a default-route redirect takes',
    '# over routing and several tunnels then fight over it, and one pushing a large private range',
    '# captures the management network. Observed: servers pushing both 10.0.0.0/8 and 192.168.0.0/16.',
    '# This daemon provides an interface; the core decides routing.',
    '',
    owned,
    '',
  ];

  if (input.remotes.length > 0) {
    lines.push(
      '# The remotes below replace the ones in the supplied profile, in the order they are listed:',
      '# that order is the failover order and it is data in the profile, not text in this file.',
      ...input.remotes.map((remote) => `# ${remote.note}`),
      ...input.remotes.map((remote) => `remote ${remote.host} ${remote.port}`),
      '',
    );
  }

  lines.push(
    `dev ${input.interfaceName}`,
    'dev-type tun',
    // `route-noexec` stops the peer's routes being installed; the two `pull-filter` lines drop the
    // dangerous ones before they are even parsed. Between them the peer cannot touch the routing table.
    'route-noexec',
    'pull-filter ignore "redirect-gateway"',
    'pull-filter ignore "route "',
    //
    // **Deliberately not `route-nopull`.** It reads like the strongest possible statement of the same
    // intention and it is not: OpenVPN's `--route-nopull` discards *every* pulled option, including
    // `dhcp-option DNS` — the one thing this configuration exists to capture.
    //
    // Measured on the bench board, 2026-09-21, against a real OpenVPN 2.6.14 peer pushing
    // `route 192.168.77.0/24`, `redirect-gateway def1` and `dhcp-option DNS 10.99.0.1`: with
    // `route-nopull` present the routing table was correctly untouched and the captured resolver file
    // was **empty**. The two directives contradicted each other, and the contradiction was invisible
    // because each half looked right on its own.
  );

  if (input.auth !== undefined) {
    lines.push(`auth-user-pass ${PATHS.openvpnDir}/${input.tunnelId}.auth`);
  }

  lines.push(
    // A route of our own, never installed, so that OpenVPN exports the peer's gateway to the up-script.
    //
    // Measured with OpenVPN 2.6.14, 2026-09-24 (`test/fixtures/openvpn/`): with the peer's routes
    // filtered and no `route` line of our own, the client builds no route list, and `route_vpn_gateway`
    // is **absent** from the up-script's environment — although the PUSH_REPLY carried
    // `route-gateway 10.136.0.1`. With this line it is present (`10.136.0.1` for a `topology subnet` peer,
    // the point-to-point peer `10.136.0.5` for `net30`), and `ip route` shows 192.0.2.1 installed in
    // neither case, because `route-noexec` stands on the unit's command line and in this file. The
    // address is TEST-NET-1 (RFC 5737), so even a client started without `route-noexec` would send one
    // documentation address into the tunnel and nothing else.
    'route 192.0.2.1 255.255.255.255',
    // The link receive counter, rewritten every five seconds: how long since the peer last sent anything
    // is read from it (`platform/tunnel-readings.ts`). Last in the file, so it wins over a `status` line
    // in the owner's profile — a peer cannot push this directive.
    `status ${PATHS.openvpnStatusDir}/${input.tunnelId}.status 5`,
  );

  return `${lines.join('\n')}\n`;
}
