/**
 * G6: the blast radius follows the rule `docs/06` states, for the diff shapes the bench board produced.
 *
 * Measured 2026-09-22. Three applies — adding an outbound, changing an outbound's server and port,
 * removing an outbound (`1b87739bc7c85899`, `c77ac7f27f86a096`, `d03414ffe34327ff`) — each came with
 * the warning *"this change reconfigures wlx90de8047b4b4, wfwan0, which is carrying the connection you
 * are using right now. You will probably lose access while it applies."* Every change set was the core
 * configuration plus a `wf-core` restart, and the access point never went down. The removal was also
 * classified `network`, though none of the pointers that moved is a reachability pointer.
 *
 * Two defects, both in `differ.ts`, and each test below names which one it catches:
 *
 * * **the class**: a routing rule added or removed shifts every later rule's index, and a later rule
 *   carrying `ip_cidr` then reads as an address list that appeared — `reachabilityView`;
 * * **the warning**: it fired whenever any desired `.network` file named a management interface,
 *   whether or not this plan touched networkd at all — `reconfiguresLinks`.
 *
 * The fixtures are generated by the real planner and diffed by the real differ against a reality that
 * is the previous plan applied, which is the shape the board runs. The profile mirrors the bench's:
 * an access point on the USB radio, a Wi-Fi uplink, the `relay` alternative, and two resource tunnels
 * — `russia` by name, `hq` by name **and address** — with `russia` listed first, so that its rule
 * sits above the hq's address rule exactly as the index shift needs.
 *
 * The other half is the asymmetry: a change to what really decides reachability must still come out
 * `network`, because a real network change classified `service` opens no window and can lock the owner
 * out with no way back.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { emptyProfile, type ProfileDocument } from '@wayfarer/schemas';
import { plan } from '../src/core/planner.ts';
import { emitTunnels } from '../src/core/emit.ts';
import { classifyContentChange, diff, type Plan2, type Reality } from '../src/core/differ.ts';
import { PATHS } from '../src/core/desired-state.ts';
import { builtInAndDongle, cleanFacts } from './helpers/synthetic-inventory.ts';

const now = (): string => '2026-09-22T19:00:00.000Z';

const RELAY = {
  id: 'relay', name: 'Relay', role: 'alternative', onUnavailable: 'block', enabled: true, protocol: 'vless',
  config: { server: '198.51.100.7', port: 443, id: 'a-placeholder-account', network: 'tcp', security: 'tls' },
};
const RUSSIA = {
  id: 'russia', name: 'Russia', role: 'resource', onUnavailable: 'block', enabled: true, protocol: 'vless',
  config: { server: '198.51.100.9', port: 443, id: 'another-placeholder', network: 'tcp', security: 'tls' },
  resources: { domainSuffix: ['.ru'] },
};
const HQ = {
  id: 'hq', name: 'HQ', role: 'resource', onUnavailable: 'block', enabled: true, protocol: 'openvpn',
  config: { profile: 'client\ndev tun\nremote hq.example.net 1194\n', interfaceSuffix: '0' },
  resources: { domainSuffix: ['.hq.example'], ipCidr: ['10.0.0.0/8'] },
};

function bench(tunnels: unknown[]): ProfileDocument {
  const base = emptyProfile({ name: 'Bench', now });
  return {
    ...base,
    accessPoint: {
      bind: { by: 'phy-usb', value: '0e8d:7961' },
      radio: { band: '5GHz', channel: 36, width: 80, country: 'US', hidden: false },
      ssid: 'Wayfarer',
      passphrase: 'a-passphrase-for-the-test',
      acceptChannelFollowsUplink: false,
    },
    uplinks: [
      { id: 'wan-wifi', kind: 'wifi-sta', priority: 20, enabled: true, bind: { by: 'phy-builtin' }, config: { ssid: 'Upstream', psk: 'upstream-secret', band: '5GHz' } },
    ],
    tunnels,
  } as unknown as ProfileDocument;
}

function planned(profile: ProfileDocument) {
  const emitted = emitTunnels({
    profile,
    core: { known: false, outboundTypes: new Set() },
    installed: new Set(['openvpn', 'ck-client', 'xray', 'sing-box']),
    allocatedPorts: new Set(),
  });
  return plan({
    profile,
    inventory: builtInAndDongle(),
    facts: { ...cleanFacts(), uplinkNetworks: [{ interface: 'wlan0', cidr: '192.168.77.0/24' }] },
    emissions: emitted.emissions,
    ports: emitted.ports,
    refusals: emitted.refusals,
    carriers: emitted.carriers,
    managementPort: 8088,
    timePorts: [123],
    coreBinaryPath: '/usr/bin/sing-box',
    upScriptPath: '/opt/wayfarer/bin/tunnel-up',
    wayBinary: '/usr/local/bin/way',
  });
}

/** The device after `desired` was applied: every file on disk, every unit in its state. */
function applied(desired: ReturnType<typeof plan>['desired']): Reality {
  const sysctl: Record<string, string> = {};
  for (const setting of desired.sysctl) sysctl[setting.key] = setting.value;
  return {
    files: [...desired.files, ...desired.networkFiles].map((file) => ({ path: file.path, content: file.content, mode: file.mode })),
    units: desired.units.map((unit) => {
      const template = unit.name.includes('@.');
      return { name: unit.name, active: template ? false : unit.active, enabled: template ? false : unit.enabled, known: !template };
    }),
    interfaces: builtInAndDongle().interfaces.map((entry) => ({ name: entry.name, mac: entry.mac })),
    // Both interfaces the session runs over: the access point and the uplink.
    managementInterfaces: builtInAndDongle().interfaces.map((entry) => entry.name).filter((name) => name.startsWith('wl')),
    sysctl,
  };
}

function change(from: ProfileDocument, to: ProfileDocument): Plan2 {
  return diff({ desired: planned(to).desired, reality: applied(planned(from).desired) });
}

/** The guard that keeps every assertion below from going vacuous: this is the measured change set. */
function assertCoreOnly(result: Plan2): void {
  assert.deepEqual(result.fileChanges.map((entry) => entry.path), [PATHS.coreConfig], 'the fixture no longer reproduces the measured change set');
  assert.deepEqual(result.unitChanges.map((entry) => `${entry.action} ${entry.name}`), ['restart wf-core.service']);
  assert.equal(result.sysctlChanges.length, 0);
  assert.equal(result.interfaceRenames.length, 0);
  assert.ok(result.affectsManagementInterfaces !== undefined);
}

function assertNoWarning(result: Plan2): void {
  // Mutation: remove `reconfiguresLinks &&` from the management-interface filter in `diff` and this
  // goes red naming both wireless interfaces.
  assert.deepEqual(result.affectsManagementInterfaces, [], `warned about ${result.affectsManagementInterfaces.join(', ')}`);
  assert.equal(result.humanDiff.some((line) => line.startsWith('WARNING')), false, result.humanDiff[0] ?? '');
}

const WITH = bench([RELAY, RUSSIA, HQ]);
const WITHOUT = bench([RELAY, HQ]);

test('G6: removing an outbound — two outbounds, one rule, one selector member — is service, with no warning', () => {
  const result = change(WITH, WITHOUT);
  assertCoreOnly(result);
  // Mutation: in `classifyContentChange`, read `JSON.parse(before)` / `JSON.parse(after)` directly
  // instead of through `reachabilityView`, and this goes red with `network` — the board's answer.
  assert.equal(result.fileChanges[0]!.blastRadius, 'service', 'the core configuration change was classified network');
  assert.equal(result.blastRadius, 'service');
  assertNoWarning(result);
});

test('G6: adding an outbound is service, with no warning', () => {
  const result = change(WITHOUT, WITH);
  assertCoreOnly(result);
  assert.equal(result.blastRadius, 'service');
  assertNoWarning(result);
});

test('G6: changing an outbound server and port is service, with no warning', () => {
  const moved = bench([RELAY, { ...RUSSIA, config: { ...RUSSIA.config, server: '203.0.113.5', port: 8443 } }, HQ]);
  const result = change(WITH, moved);
  assertCoreOnly(result);
  // This shape was already `service` in the differ before this change; what was wrong about it on the
  // board was the warning, which is what goes red without the fix.
  assert.equal(result.blastRadius, 'service');
  assertNoWarning(result);
});

/* ── the asymmetry: what really decides reachability is still network ────────────────────── */

const BASE = planned(WITH).desired.files.find((file) => file.path === PATHS.coreConfig)!.content;

function edited(edit: (document: Record<string, any>) => void): string {
  const document = JSON.parse(BASE) as Record<string, any>;
  edit(document);
  const after = JSON.stringify(document);
  assert.notEqual(after, BASE, 'the edit changed nothing, so the assertion after it would be vacuous');
  return after;
}

const NETWORKS = planned(WITH).desired.reachabilityNetworks;

test('G6: the tun inbound exclusion list changing is still network', () => {
  const after = edited((document) => {
    document.inbounds[0].route_exclude_address = [...document.inbounds[0].route_exclude_address, '198.18.0.0/15'];
  });
  assert.equal(classifyContentChange(PATHS.coreConfig, BASE, after, NETWORKS), 'network');
});

test('G6: the tun inbound address changing is still network', () => {
  // `inet4_address` in older cores, `address` in 1.14; either lives under `/inbounds`.
  const after = edited((document) => {
    document.inbounds[0].address = ['172.19.9.1/30'];
  });
  assert.equal(classifyContentChange(PATHS.coreConfig, BASE, after, NETWORKS), 'network');
});

test('G6: a listening inbound on an address the management session uses is still network', () => {
  const after = edited((document) => {
    document.inbounds.push({ type: 'mixed', tag: 'lan-proxy', listen: '192.168.77.8', listen_port: 8088 });
  });
  assert.equal(classifyContentChange(PATHS.coreConfig, BASE, after, NETWORKS), 'network');
});

test('G6: a routing rule that names addresses, added, removed or reordered, is still network', () => {
  const addressRules = (document: Record<string, any>): number[] =>
    (document.route.rules as Record<string, unknown>[]).flatMap((rule, index) => ('ip_cidr' in rule ? [index] : []));
  assert.ok(addressRules(JSON.parse(BASE)).length >= 2, 'the fixture needs two address rules to reorder');

  const added = edited((document) => {
    document.route.rules.splice(2, 0, { ip_cidr: ['198.18.0.0/15'], outbound: 'relay' });
  });
  // Mutation: make `reachabilityView` drop address rules too (filter to `false`) and these go red.
  assert.equal(classifyContentChange(PATHS.coreConfig, BASE, added, NETWORKS), 'network', 'an address rule added');

  const removed = edited((document) => {
    const last = addressRules(document).at(-1)!;
    document.route.rules.splice(last, 1);
  });
  assert.equal(classifyContentChange(PATHS.coreConfig, BASE, removed, NETWORKS), 'network', 'an address rule removed');

  const reordered = edited((document) => {
    const [first, second] = addressRules(document) as [number, number];
    const rules = document.route.rules as unknown[];
    [rules[first], rules[second]] = [rules[second], rules[first]];
  });
  assert.equal(classifyContentChange(PATHS.coreConfig, BASE, reordered, NETWORKS), 'network', 'address rules reordered');
});

test('G6: a change that does rewrite networkd still warns about the management interfaces', () => {
  // The warning's other half: when the plan does reconfigure links, it must still say so.
  const moved = { ...WITH, network: { ...WITH.network, cidr: '10.45.0.0/24' } } as ProfileDocument;
  const result = change(WITH, moved);
  assert.ok(result.fileChanges.some((entry) => entry.path.startsWith(`${PATHS.networkdDir}/`)), 'the fixture should rewrite a networkd file');
  assert.equal(result.blastRadius, 'network');
  assert.ok(result.affectsManagementInterfaces.length > 0, 'a networkd rewrite no longer warns');
  assert.ok(result.humanDiff[0]!.startsWith('WARNING'));
});
